name: Checkstyle on Dev PR
on: 
  workflow_dispatch:
  pull_request_target:
    branches:
      - master
      - CLN-[0-9]?
      - DEV_*
    paths:
      - '**/*.java'
      - '**/*.feature'
      - '**/test/resources/**'
      - '**/pom.xml'
      - '**/*.json'


 
jobs:
  build:
    name: Basic smoke test
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name
      id: branch-name
      run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
    - name: CheckOutRepo
      uses: actions/checkout@v2
      with:
        ref: ${{steps.branch-name.outputs.branch}}
