name: Checkstyle on Dev PR
on: 
  workflow_dispatch:
  pull_request_target:
    branches:
      - master
      - CLN-[0-9]?
    paths:
      - '**/*.java'
      - '**/*.feature'
      - '**/test/resources/**'
      - '**/pom.xml'
      - '**/*.json'

jobs:
  build:
    name: Basic smoke test test
    runs-on: ubuntu-latest
    steps:
    - name: Get branch name test
      id: branch-name
      run: git fetch --depth 1 $GITHUB_REF
    - name: CheckOutRepo
      uses: actions/checkout@v2
      with:
        ref: ${{steps.branch-name.outputs.branch}}
      run: echo "${{steps.branch-name.outputs.branch}}"
    - name: Get branch name test2
      id: branch-name
      run: echo "$GITHUB_REF"
      
